name: neucon
channels:
  # You can use the TUNA mirror to speed up the installation if you are in mainland China.
  # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - pytorch-lts
  - defaults
  - conda-forge
dependencies:
  - backports.weakref
  - backports.cached-property
  - python=3.7.9
  - pytorch
  - torchvision
  - cudatoolkit=11.1
  - ipython
  - tqdm
  - numba
  - pip
  - pip:
    - -r requirements.txt
    - git+https://github.com/mit-han-lab/torchsparse.git
